### ISSUE TITLE
Pin requirements.txt and requirements.yml to specific versions

### ISSUE THREAD

**Issue by seancannata** [RedHatGov/ansible-tower-samples#3]
```
# requirements.txt example
pandas==1.0.4
pyparsing==2.4.7          # via matplotlib
python-dateutil==2.8.1    # via matplotlib, pandas
pytz==2020.1              # via pandas
scipy==1.4.1              # via seaborn
seaborn==0.10.1
six==1.15.0               # via cycler, python-dateutil
```

```
## requirements.yml example

---
collections:
  - name: community.aws
    version: 1.5.0 
  - ansible.windows
  # - community.windows
  - name: amazon.aws
    version: 3.0.0
  - name: ansible.controller
    version: 4.1.0 
  - containers.podman
  # - ansible.tower
  - community.general
```
